# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'finance_Ui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_finance(object):
    def setupUi(self, finance):
        finance.setObjectName("finance")
        finance.resize(842, 584)
        self.centralwidget = QtWidgets.QWidget(finance)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 60, 821, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(200, 20, 441, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 161, 21))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(800, 70, 20, 471))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(100, 80, 641, 231))
        self.groupBox_2.setObjectName("groupBox_2")
        self.graphicsView = QtWidgets.QGraphicsView(self.groupBox_2)
        self.graphicsView.setGeometry(QtCore.QRect(50, 20, 551, 211))
        self.graphicsView.setObjectName("graphicsView")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(100, 310, 641, 221))
        self.groupBox_3.setObjectName("groupBox_3")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_3)
        self.tableWidget.setGeometry(QtCore.QRect(50, 20, 551, 201))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 70, 771, 481))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(20, 70, 20, 471))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        finance.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(finance)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 842, 23))
        self.menubar.setObjectName("menubar")
        finance.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(finance)
        self.statusbar.setObjectName("statusbar")
        finance.setStatusBar(self.statusbar)

        self.retranslateUi(finance)
        QtCore.QMetaObject.connectSlotsByName(finance)

    def retranslateUi(self, finance):
        _translate = QtCore.QCoreApplication.translate
        finance.setWindowTitle(_translate("finance", "MainWindow"))
        self.label.setText(_translate("finance", "   请输入："))
        self.comboBox.setItemText(0, _translate("finance", "按年"))
        self.comboBox.setItemText(1, _translate("finance", "按月"))
        self.comboBox.setItemText(2, _translate("finance", "按日"))
        self.pushButton.setText(_translate("finance", "查看财务"))
        self.groupBox_2.setTitle(_translate("finance", "财务折线统计"))
        self.groupBox_3.setTitle(_translate("finance", "财务详情"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("finance", "车位号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("finance", "缴费时间"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("finance", "金额（元）"))

