# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register_Ui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_register_2(object):
    def setupUi(self, register_2):
        register_2.setObjectName("register_2")
        register_2.resize(619, 423)
        self.gridLayoutWidget = QtWidgets.QWidget(register_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(190, 60, 241, 251))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.surePwdlineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.surePwdlineEdit.setObjectName("surePwdlineEdit")
        self.gridLayout.addWidget(self.surePwdlineEdit, 3, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 8, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.namelineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.namelineEdit.setObjectName("namelineEdit")
        self.gridLayout.addWidget(self.namelineEdit, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.nan_radioButton = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.nan_radioButton.setObjectName("nan_radioButton")
        self.horizontalLayout_2.addWidget(self.nan_radioButton)
        self.nv_radioButton = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.nv_radioButton.setObjectName("nv_radioButton")
        self.horizontalLayout_2.addWidget(self.nv_radioButton)
        self.gridLayout.addLayout(self.horizontalLayout_2, 6, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        self.phonelineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.phonelineEdit.setObjectName("phonelineEdit")
        self.gridLayout.addWidget(self.phonelineEdit, 5, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 9, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.pwdlineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.pwdlineEdit.setObjectName("pwdlineEdit")
        self.gridLayout.addWidget(self.pwdlineEdit, 2, 1, 1, 1)
        self.emalineEdit_3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.emalineEdit_3.setObjectName("emalineEdit_3")
        self.gridLayout.addWidget(self.emalineEdit_3, 9, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 8, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 7, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout.addWidget(self.comboBox_2, 7, 1, 1, 1)
        self.layoutWidget = QtWidgets.QWidget(register_2)
        self.layoutWidget.setGeometry(QtCore.QRect(250, 340, 179, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.firmpushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.firmpushButton_2.setObjectName("firmpushButton_2")
        self.horizontalLayout.addWidget(self.firmpushButton_2)
        self.concelpushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.concelpushButton.setObjectName("concelpushButton")
        self.horizontalLayout.addWidget(self.concelpushButton)

        self.retranslateUi(register_2)
        QtCore.QMetaObject.connectSlotsByName(register_2)

    def retranslateUi(self, register_2):
        _translate = QtCore.QCoreApplication.translate
        register_2.setWindowTitle(_translate("register_2", "Form"))
        self.comboBox.setItemText(0, _translate("register_2", "天气"))
        self.comboBox.setItemText(1, _translate("register_2", "我的生日"))
        self.comboBox.setItemText(2, _translate("register_2", "我的电话"))
        self.comboBox.setItemText(3, _translate("register_2", "我父亲的电话"))
        self.comboBox.setItemText(4, _translate("register_2", "我母亲的电话"))
        self.label_2.setText(_translate("register_2", " 密    码："))
        self.label_6.setText(_translate("register_2", " 确认密码："))
        self.nan_radioButton.setText(_translate("register_2", " 男  "))
        self.nv_radioButton.setText(_translate("register_2", " 女"))
        self.label_5.setText(_translate("register_2", " 性    别："))
        self.label_3.setText(_translate("register_2", " 密保答案："))
        self.label.setText(_translate("register_2", " 账    户："))
        self.label_4.setText(_translate("register_2", " 电    话："))
        self.label_7.setText(_translate("register_2", " 密保问题："))
        self.label_8.setText(_translate("register_2", " 身    份："))
        self.comboBox_2.setItemText(0, _translate("register_2", "财务管理员"))
        self.comboBox_2.setItemText(1, _translate("register_2", "信息管理员"))
        self.comboBox_2.setItemText(2, _translate("register_2", "停车场管理员"))
        self.firmpushButton_2.setText(_translate("register_2", "确 定"))
        self.concelpushButton.setText(_translate("register_2", "取消"))

