# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'seatManage.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_seat(object):
    def setupUi(self, seat):
        seat.setObjectName("seat")
        seat.resize(731, 450)
        self.line = QtWidgets.QFrame(seat)
        self.line.setGeometry(QtCore.QRect(30, 20, 661, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(seat)
        self.line_2.setGeometry(QtCore.QRect(180, 50, 20, 351))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.groupBox = QtWidgets.QGroupBox(seat)
        self.groupBox.setGeometry(QtCore.QRect(40, 40, 120, 171))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 190, 160, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 91, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.label = QtWidgets.QLabel(seat)
        self.label.setGeometry(QtCore.QRect(190, 30, 541, 411))
        self.label.setText("")
        self.label.setObjectName("label")
        self.tableWidget_3 = QtWidgets.QTableWidget(seat)
        self.tableWidget_3.setGeometry(QtCore.QRect(200, 80, 461, 171))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(5)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        self.tableWidget_2 = QtWidgets.QTableWidget(seat)
        self.tableWidget_2.setGeometry(QtCore.QRect(280, 100, 281, 51))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(2)
        self.tableWidget_2.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        self.groupBox_2 = QtWidgets.QGroupBox(seat)
        self.groupBox_2.setGeometry(QtCore.QRect(250, 120, 401, 171))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableWidget_4.setGeometry(QtCore.QRect(40, 50, 311, 111))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(3)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(30, 10, 331, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_3.addWidget(self.lineEdit_4)
        self.comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget_3)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.pushButton_8 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_3.addWidget(self.pushButton_8)
        self.tableWidget_4.raise_()
        self.tableWidget_3.raise_()
        self.tableWidget_3.raise_()
        self.horizontalLayoutWidget_3.raise_()
        self.groupBox_3 = QtWidgets.QGroupBox(seat)
        self.groupBox_3.setGeometry(QtCore.QRect(290, 240, 281, 131))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(37, 10, 221, 121))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_2.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_2.addWidget(self.pushButton_6)
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 3, 1, 1, 1)

        self.retranslateUi(seat)
        QtCore.QMetaObject.connectSlotsByName(seat)

    def retranslateUi(self, seat):
        _translate = QtCore.QCoreApplication.translate
        seat.setWindowTitle(_translate("seat", "Form"))
        self.pushButton.setText(_translate("seat", "车位设置"))
        self.pushButton_2.setText(_translate("seat", "车位锁状态"))
        self.pushButton_3.setText(_translate("seat", "车位操作"))
        self.pushButton_4.setText(_translate("seat", "车位初始详情"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("seat", "车位号"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("seat", "车位锁状态"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("seat", "车辆占用"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("seat", "车辆类型"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("seat", "状态操作"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("seat", "已占车位(个)"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("seat", "内部车位"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("seat", "外部车位"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("seat", "车位号"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("seat", "车位类型"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("seat", "操作"))
        self.label_5.setText(_translate("seat", "请输入"))
        self.comboBox.setItemText(0, _translate("seat", "车位号"))
        self.comboBox.setItemText(1, _translate("seat", "员工车位"))
        self.comboBox.setItemText(2, _translate("seat", "临时车位"))
        self.pushButton_8.setText(_translate("seat", "检索"))
        self.label_4.setText(_translate("seat", "外部车辆数："))
        self.label_3.setText(_translate("seat", "内部车辆数："))
        self.label_2.setText(_translate("seat", "  车位总数："))
        self.pushButton_6.setText(_translate("seat", "确  定"))
        self.pushButton_5.setText(_translate("seat", "取  消"))

